name: Build Image

on:
  pull_request: {}
  push:
    branches:
      - main
    paths:
      - chart/Chart.yaml

env:
  # The path to the Chart.yaml file
  CHART_YAML_DIRECTORY: chart/Chart.yaml

  # Name of the docker image
  DOCKER_IMAGE_NAME: test-chart
  # Path to the Dockerfile
  DOCKER_FILE_PATH: Dockerfile
  # The docker context
  DOCKER_CONTEXT: .


jobs:
  # Get the following values from the chart/Chart.yaml file
  # - chart version
  # - app version (Also known as docker image tag)
  resolve-versions:
    name: Resolve versions
    runs-on: ubuntu-latest
    outputs:
      chart-version: ${{ steps.resolve-chart.outputs.semver }}
      image-tag: ${{ steps.resolve-image.outputs.semver }}
    steps:
      - uses: actions/checkout@v3

      - name: Resolve chart version
        id: resolve-chart
        uses: Energinet-DataHub/.github/.github/actions/get-semver@main
        with:
          yaml_file: ${{ env.CHART_YAML_DIRECTORY }}
          yaml_path: version

      - name: Resolve image version
        id: resolve-image
        uses: Energinet-DataHub/.github/.github/actions/get-semver@main
        with:
          yaml_file: ${{ env.CHART_YAML_DIRECTORY }}
          yaml_path: appVersion


  build_and_publish_docker_image:
    name: Publish and publish docker image
    needs:
      - resolve-versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        uses: Energinet-DataHub/.github/.github/actions/build-and-push-container@main
        with:
          dockerfile: ${{ env.DOCKER_FILE_PATH }}
          image-name: ${{ env.DOCKER_IMAGE_NAME }}
          image-tag: ${{ needs.resolve-versions.outputs.image-tag }}
          docker-context: ${{ env.DOCKER_CONTEXT }}